name: build and deploy spring-api
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: build and deploy examination project
    runs-on: ubuntu-20.04
    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: mvn clean
        run: mvn -B clean --file pom.xml

      - name: unit tests
        run: mvn -B test --file pom.xml